{{- if and (not .Values.protection.cookieSecret.existingSecret) .Values.protection.cookieSecret.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pagedrop-host.fullname" . }}-cookie
  labels:
    {{- include "pagedrop-host.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "pagedrop-host.cookieSecretKey" . }}: {{ .Values.protection.cookieSecret.value | quote }}
{{- end }}
