apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pagedrop-host.fullname" . }}-data
  labels:
    {{- include "pagedrop-host.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- with .Values.storage.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
